### ISSUE TITLE
Configurable Cache fore NetherPortalSearcher.java

### ISSUE THREAD

**Issue by thojo0** [bergerhealer/MyWorlds#37]
A world specific configuration to enable/disable/change the cache lifetime + cache search range would be nice.

So basicly:
 - CACHE_LIFETIME
 - LOAD_LIFETIME
 - the 32 and maybe the 4 too: https://github.com/bergerhealer/MyWorlds/blob/51440dedde9bea1e54976c34d6aef670ada5d1f2/src/main/java/com/bergerkiller/bukkit/mw/portal/NetherPortalSearcher.java#L198
 - radius (because I saw the comment 😉): https://github.com/bergerhealer/MyWorlds/blob/51440dedde9bea1e54976c34d6aef670ada5d1f2/src/main/java/com/bergerkiller/bukkit/mw/portal/NetherPortalSearcher.java#L259

**Comment by bergerkiller** [comment]
I don't really see the use of making these things configurable. Is there a measurable reason to do so? Keep in mind that for actual searching, it defers to Minecraft servers own search, for which paper's (per-world) portal search configuration already applies.

Searching for portals also isn't as laggy as it used to be, as nowadays that information is tracked in the POI (point of interest) files.

**Comment by bergerkiller** [comment]
The LOAD_LIFETIME might be interesting to make configurable I guess, as it reduces the number of times the chunk area in the nether/overworld load and unload as people come and go.

**Comment by thojo0** [comment]
First of all, I'm the opinion to make thinks configurable if posible.

But I try to explain the problem which happend to me:
If you link 2 worlds by netherportal-linking it is posible that you exit on the wrong portal.
This is a Problem in classic portal chunk loader setups.

**Steps to reproduce:**
1. Enter red Portal in overworld
2. Go through any portal back (both working fine from nether->overworld)
3. Enter green Portal in overworld in the next 5 seconds
4. You will exit the red Portal in the nether
5. (You can repeat this with the other way arround to)

![2023-02-15_09 14 08](https://user-images.githubusercontent.com/53666000/218970877-fb52ba87-e92b-444d-acc1-8eecb2489537.png)
![2023-02-15_09 14 23](https://user-images.githubusercontent.com/53666000/218970892-064ade66-6018-45af-993a-b53196e930c2.png)

**Comment by bergerkiller** [comment]
I see, feels more like I need to get rid of that 32x4x32 way of caching entirely then. I'll have to fix that as using portals like this is common for nether-hub systems.

**Comment by thojo0** [comment]
Is this still in doing and planed or whats the current state?

**Comment by bergerkiller** [comment]
oh, I kinda forgot. One sec

**Comment by bergerkiller** [comment]
https://ci.mg-dev.eu/job/MyWorlds/304/

Adds a config.yml option:

```
# MyWorlds caches destinations for portals frequently entered to minimize lag
# When a portal block is activated near to a previously activated one, search results are reused
# The width and height control the sensitivity of matching these results
# If a wrong portal is entered because of this, you can lower these values to fix that
portalSearchMatchRadius:
  width: 32
  height: 4
```
